/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
)

// DeploymentsStgWestDeploymentEnvironment struct for DeploymentsStgWestDeploymentEnvironment
type DeploymentsStgWestDeploymentEnvironment struct {
	Object
	// The UUID identifying the environment.
	Uuid *string `json:"uuid,omitempty"`
	// The name of the environment.
	Name *string `json:"name,omitempty"`
}

// NewDeploymentsStgWestDeploymentEnvironment instantiates a new DeploymentsStgWestDeploymentEnvironment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentsStgWestDeploymentEnvironment() *DeploymentsStgWestDeploymentEnvironment {
	this := DeploymentsStgWestDeploymentEnvironment{}
	return &this
}

// NewDeploymentsStgWestDeploymentEnvironmentWithDefaults instantiates a new DeploymentsStgWestDeploymentEnvironment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentsStgWestDeploymentEnvironmentWithDefaults() *DeploymentsStgWestDeploymentEnvironment {
	this := DeploymentsStgWestDeploymentEnvironment{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *DeploymentsStgWestDeploymentEnvironment) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentsStgWestDeploymentEnvironment) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *DeploymentsStgWestDeploymentEnvironment) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *DeploymentsStgWestDeploymentEnvironment) SetUuid(v string) {
	o.Uuid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeploymentsStgWestDeploymentEnvironment) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentsStgWestDeploymentEnvironment) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeploymentsStgWestDeploymentEnvironment) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeploymentsStgWestDeploymentEnvironment) SetName(v string) {
	o.Name = &v
}

func (o DeploymentsStgWestDeploymentEnvironment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}
	if o.Uuid != nil {
		toSerialize["uuid"] = o.Uuid
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentsStgWestDeploymentEnvironment struct {
	value *DeploymentsStgWestDeploymentEnvironment
	isSet bool
}

func (v NullableDeploymentsStgWestDeploymentEnvironment) Get() *DeploymentsStgWestDeploymentEnvironment {
	return v.value
}

func (v *NullableDeploymentsStgWestDeploymentEnvironment) Set(val *DeploymentsStgWestDeploymentEnvironment) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentsStgWestDeploymentEnvironment) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentsStgWestDeploymentEnvironment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentsStgWestDeploymentEnvironment(val *DeploymentsStgWestDeploymentEnvironment) *NullableDeploymentsStgWestDeploymentEnvironment {
	return &NullableDeploymentsStgWestDeploymentEnvironment{value: val, isSet: true}
}

func (v NullableDeploymentsStgWestDeploymentEnvironment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentsStgWestDeploymentEnvironment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


