/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// DdevReport struct for DdevReport
type DdevReport struct {
	Object
	AdditionalProperties map[string]interface{}
}

type _DdevReport DdevReport

// NewDdevReport instantiates a new DdevReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDdevReport() *DdevReport {
	this := DdevReport{}
	return &this
}

// NewDdevReportWithDefaults instantiates a new DdevReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDdevReportWithDefaults() *DdevReport {
	this := DdevReport{}
	return &this
}

func (o DdevReport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *DdevReport) UnmarshalJSON(bytes []byte) (err error) {
	type DdevReportWithoutEmbeddedStruct struct {
	}

	varDdevReportWithoutEmbeddedStruct := DdevReportWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varDdevReportWithoutEmbeddedStruct)
	if err == nil {
		varDdevReport := _DdevReport{}
		*o = DdevReport(varDdevReport)
	} else {
		return err
	}

	varDdevReport := _DdevReport{}

	err = json.Unmarshal(bytes, &varDdevReport)
	if err == nil {
		o.Object = varDdevReport.Object
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectObject := reflect.ValueOf(o.Object)
		for i := 0; i < reflectObject.Type().NumField(); i++ {
			t := reflectObject.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDdevReport struct {
	value *DdevReport
	isSet bool
}

func (v NullableDdevReport) Get() *DdevReport {
	return v.value
}

func (v *NullableDdevReport) Set(val *DdevReport) {
	v.value = val
	v.isSet = true
}

func (v NullableDdevReport) IsSet() bool {
	return v.isSet
}

func (v *NullableDdevReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDdevReport(val *DdevReport) *NullableDdevReport {
	return &NullableDdevReport{value: val, isSet: true}
}

func (v NullableDdevReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDdevReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


