/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineTrigger struct for PipelineTrigger
type PipelineTrigger struct {
	Object
	AdditionalProperties map[string]interface{}
}

type _PipelineTrigger PipelineTrigger

// NewPipelineTrigger instantiates a new PipelineTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineTrigger() *PipelineTrigger {
	this := PipelineTrigger{}
	return &this
}

// NewPipelineTriggerWithDefaults instantiates a new PipelineTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineTriggerWithDefaults() *PipelineTrigger {
	this := PipelineTrigger{}
	return &this
}

func (o PipelineTrigger) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineTrigger) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineTriggerWithoutEmbeddedStruct struct {
	}

	varPipelineTriggerWithoutEmbeddedStruct := PipelineTriggerWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineTriggerWithoutEmbeddedStruct)
	if err == nil {
		varPipelineTrigger := _PipelineTrigger{}
		*o = PipelineTrigger(varPipelineTrigger)
	} else {
		return err
	}

	varPipelineTrigger := _PipelineTrigger{}

	err = json.Unmarshal(bytes, &varPipelineTrigger)
	if err == nil {
		o.Object = varPipelineTrigger.Object
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectObject := reflect.ValueOf(o.Object)
		for i := 0; i < reflectObject.Type().NumField(); i++ {
			t := reflectObject.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineTrigger struct {
	value *PipelineTrigger
	isSet bool
}

func (v NullablePipelineTrigger) Get() *PipelineTrigger {
	return v.value
}

func (v *NullablePipelineTrigger) Set(val *PipelineTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineTrigger(val *PipelineTrigger) *NullablePipelineTrigger {
	return &NullablePipelineTrigger{value: val, isSet: true}
}

func (v NullablePipelineTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


