/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineStepStatePending struct for PipelineStepStatePending
type PipelineStepStatePending struct {
	PipelineStepState
	// The name of pipeline step state (PENDING).
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PipelineStepStatePending PipelineStepStatePending

// NewPipelineStepStatePending instantiates a new PipelineStepStatePending object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStepStatePending() *PipelineStepStatePending {
	this := PipelineStepStatePending{}
	return &this
}

// NewPipelineStepStatePendingWithDefaults instantiates a new PipelineStepStatePending object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStepStatePendingWithDefaults() *PipelineStepStatePending {
	this := PipelineStepStatePending{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PipelineStepStatePending) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStepStatePending) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PipelineStepStatePending) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PipelineStepStatePending) SetName(v string) {
	o.Name = &v
}

func (o PipelineStepStatePending) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedPipelineStepState, errPipelineStepState := json.Marshal(o.PipelineStepState)
	if errPipelineStepState != nil {
		return []byte{}, errPipelineStepState
	}
	errPipelineStepState = json.Unmarshal([]byte(serializedPipelineStepState), &toSerialize)
	if errPipelineStepState != nil {
		return []byte{}, errPipelineStepState
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineStepStatePending) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineStepStatePendingWithoutEmbeddedStruct struct {
		// The name of pipeline step state (PENDING).
		Name *string `json:"name,omitempty"`
	}

	varPipelineStepStatePendingWithoutEmbeddedStruct := PipelineStepStatePendingWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineStepStatePendingWithoutEmbeddedStruct)
	if err == nil {
		varPipelineStepStatePending := _PipelineStepStatePending{}
		varPipelineStepStatePending.Name = varPipelineStepStatePendingWithoutEmbeddedStruct.Name
		*o = PipelineStepStatePending(varPipelineStepStatePending)
	} else {
		return err
	}

	varPipelineStepStatePending := _PipelineStepStatePending{}

	err = json.Unmarshal(bytes, &varPipelineStepStatePending)
	if err == nil {
		o.PipelineStepState = varPipelineStepStatePending.PipelineStepState
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")

		// remove fields from embedded structs
		reflectPipelineStepState := reflect.ValueOf(o.PipelineStepState)
		for i := 0; i < reflectPipelineStepState.Type().NumField(); i++ {
			t := reflectPipelineStepState.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineStepStatePending struct {
	value *PipelineStepStatePending
	isSet bool
}

func (v NullablePipelineStepStatePending) Get() *PipelineStepStatePending {
	return v.value
}

func (v *NullablePipelineStepStatePending) Set(val *PipelineStepStatePending) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStepStatePending) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStepStatePending) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStepStatePending(val *PipelineStepStatePending) *NullablePipelineStepStatePending {
	return &NullablePipelineStepStatePending{value: val, isSet: true}
}

func (v NullablePipelineStepStatePending) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStepStatePending) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


