/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineStepState struct for PipelineStepState
type PipelineStepState struct {
	Object
	AdditionalProperties map[string]interface{}
}

type _PipelineStepState PipelineStepState

// NewPipelineStepState instantiates a new PipelineStepState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStepState() *PipelineStepState {
	this := PipelineStepState{}
	return &this
}

// NewPipelineStepStateWithDefaults instantiates a new PipelineStepState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStepStateWithDefaults() *PipelineStepState {
	this := PipelineStepState{}
	return &this
}

func (o PipelineStepState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineStepState) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineStepStateWithoutEmbeddedStruct struct {
	}

	varPipelineStepStateWithoutEmbeddedStruct := PipelineStepStateWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineStepStateWithoutEmbeddedStruct)
	if err == nil {
		varPipelineStepState := _PipelineStepState{}
		*o = PipelineStepState(varPipelineStepState)
	} else {
		return err
	}

	varPipelineStepState := _PipelineStepState{}

	err = json.Unmarshal(bytes, &varPipelineStepState)
	if err == nil {
		o.Object = varPipelineStepState.Object
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectObject := reflect.ValueOf(o.Object)
		for i := 0; i < reflectObject.Type().NumField(); i++ {
			t := reflectObject.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineStepState struct {
	value *PipelineStepState
	isSet bool
}

func (v NullablePipelineStepState) Get() *PipelineStepState {
	return v.value
}

func (v *NullablePipelineStepState) Set(val *PipelineStepState) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStepState) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStepState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStepState(val *PipelineStepState) *NullablePipelineStepState {
	return &NullablePipelineStepState{value: val, isSet: true}
}

func (v NullablePipelineStepState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStepState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


