/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineScheduleExecution struct for PipelineScheduleExecution
type PipelineScheduleExecution struct {
	Object
	AdditionalProperties map[string]interface{}
}

type _PipelineScheduleExecution PipelineScheduleExecution

// NewPipelineScheduleExecution instantiates a new PipelineScheduleExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineScheduleExecution() *PipelineScheduleExecution {
	this := PipelineScheduleExecution{}
	return &this
}

// NewPipelineScheduleExecutionWithDefaults instantiates a new PipelineScheduleExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineScheduleExecutionWithDefaults() *PipelineScheduleExecution {
	this := PipelineScheduleExecution{}
	return &this
}

func (o PipelineScheduleExecution) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineScheduleExecution) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineScheduleExecutionWithoutEmbeddedStruct struct {
	}

	varPipelineScheduleExecutionWithoutEmbeddedStruct := PipelineScheduleExecutionWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineScheduleExecutionWithoutEmbeddedStruct)
	if err == nil {
		varPipelineScheduleExecution := _PipelineScheduleExecution{}
		*o = PipelineScheduleExecution(varPipelineScheduleExecution)
	} else {
		return err
	}

	varPipelineScheduleExecution := _PipelineScheduleExecution{}

	err = json.Unmarshal(bytes, &varPipelineScheduleExecution)
	if err == nil {
		o.Object = varPipelineScheduleExecution.Object
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectObject := reflect.ValueOf(o.Object)
		for i := 0; i < reflectObject.Type().NumField(); i++ {
			t := reflectObject.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineScheduleExecution struct {
	value *PipelineScheduleExecution
	isSet bool
}

func (v NullablePipelineScheduleExecution) Get() *PipelineScheduleExecution {
	return v.value
}

func (v *NullablePipelineScheduleExecution) Set(val *PipelineScheduleExecution) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineScheduleExecution) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineScheduleExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineScheduleExecution(val *PipelineScheduleExecution) *NullablePipelineScheduleExecution {
	return &NullablePipelineScheduleExecution{value: val, isSet: true}
}

func (v NullablePipelineScheduleExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineScheduleExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


