/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineStateInProgressRunning struct for PipelineStateInProgressRunning
type PipelineStateInProgressRunning struct {
	PipelineStateInProgressStage
	// The name of the stage (RUNNING)
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PipelineStateInProgressRunning PipelineStateInProgressRunning

// NewPipelineStateInProgressRunning instantiates a new PipelineStateInProgressRunning object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStateInProgressRunning() *PipelineStateInProgressRunning {
	this := PipelineStateInProgressRunning{}
	return &this
}

// NewPipelineStateInProgressRunningWithDefaults instantiates a new PipelineStateInProgressRunning object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStateInProgressRunningWithDefaults() *PipelineStateInProgressRunning {
	this := PipelineStateInProgressRunning{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PipelineStateInProgressRunning) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStateInProgressRunning) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PipelineStateInProgressRunning) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PipelineStateInProgressRunning) SetName(v string) {
	o.Name = &v
}

func (o PipelineStateInProgressRunning) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedPipelineStateInProgressStage, errPipelineStateInProgressStage := json.Marshal(o.PipelineStateInProgressStage)
	if errPipelineStateInProgressStage != nil {
		return []byte{}, errPipelineStateInProgressStage
	}
	errPipelineStateInProgressStage = json.Unmarshal([]byte(serializedPipelineStateInProgressStage), &toSerialize)
	if errPipelineStateInProgressStage != nil {
		return []byte{}, errPipelineStateInProgressStage
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineStateInProgressRunning) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineStateInProgressRunningWithoutEmbeddedStruct struct {
		// The name of the stage (RUNNING)
		Name *string `json:"name,omitempty"`
	}

	varPipelineStateInProgressRunningWithoutEmbeddedStruct := PipelineStateInProgressRunningWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineStateInProgressRunningWithoutEmbeddedStruct)
	if err == nil {
		varPipelineStateInProgressRunning := _PipelineStateInProgressRunning{}
		varPipelineStateInProgressRunning.Name = varPipelineStateInProgressRunningWithoutEmbeddedStruct.Name
		*o = PipelineStateInProgressRunning(varPipelineStateInProgressRunning)
	} else {
		return err
	}

	varPipelineStateInProgressRunning := _PipelineStateInProgressRunning{}

	err = json.Unmarshal(bytes, &varPipelineStateInProgressRunning)
	if err == nil {
		o.PipelineStateInProgressStage = varPipelineStateInProgressRunning.PipelineStateInProgressStage
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")

		// remove fields from embedded structs
		reflectPipelineStateInProgressStage := reflect.ValueOf(o.PipelineStateInProgressStage)
		for i := 0; i < reflectPipelineStateInProgressStage.Type().NumField(); i++ {
			t := reflectPipelineStateInProgressStage.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineStateInProgressRunning struct {
	value *PipelineStateInProgressRunning
	isSet bool
}

func (v NullablePipelineStateInProgressRunning) Get() *PipelineStateInProgressRunning {
	return v.value
}

func (v *NullablePipelineStateInProgressRunning) Set(val *PipelineStateInProgressRunning) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStateInProgressRunning) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStateInProgressRunning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStateInProgressRunning(val *PipelineStateInProgressRunning) *NullablePipelineStateInProgressRunning {
	return &NullablePipelineStateInProgressRunning{value: val, isSet: true}
}

func (v NullablePipelineStateInProgressRunning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStateInProgressRunning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


