/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineStepStateCompletedExpired struct for PipelineStepStateCompletedExpired
type PipelineStepStateCompletedExpired struct {
	PipelineStepStateCompletedResult
	// The name of the result (EXPIRED)
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PipelineStepStateCompletedExpired PipelineStepStateCompletedExpired

// NewPipelineStepStateCompletedExpired instantiates a new PipelineStepStateCompletedExpired object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStepStateCompletedExpired() *PipelineStepStateCompletedExpired {
	this := PipelineStepStateCompletedExpired{}
	return &this
}

// NewPipelineStepStateCompletedExpiredWithDefaults instantiates a new PipelineStepStateCompletedExpired object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStepStateCompletedExpiredWithDefaults() *PipelineStepStateCompletedExpired {
	this := PipelineStepStateCompletedExpired{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PipelineStepStateCompletedExpired) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStepStateCompletedExpired) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PipelineStepStateCompletedExpired) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PipelineStepStateCompletedExpired) SetName(v string) {
	o.Name = &v
}

func (o PipelineStepStateCompletedExpired) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedPipelineStepStateCompletedResult, errPipelineStepStateCompletedResult := json.Marshal(o.PipelineStepStateCompletedResult)
	if errPipelineStepStateCompletedResult != nil {
		return []byte{}, errPipelineStepStateCompletedResult
	}
	errPipelineStepStateCompletedResult = json.Unmarshal([]byte(serializedPipelineStepStateCompletedResult), &toSerialize)
	if errPipelineStepStateCompletedResult != nil {
		return []byte{}, errPipelineStepStateCompletedResult
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineStepStateCompletedExpired) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineStepStateCompletedExpiredWithoutEmbeddedStruct struct {
		// The name of the result (EXPIRED)
		Name *string `json:"name,omitempty"`
	}

	varPipelineStepStateCompletedExpiredWithoutEmbeddedStruct := PipelineStepStateCompletedExpiredWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineStepStateCompletedExpiredWithoutEmbeddedStruct)
	if err == nil {
		varPipelineStepStateCompletedExpired := _PipelineStepStateCompletedExpired{}
		varPipelineStepStateCompletedExpired.Name = varPipelineStepStateCompletedExpiredWithoutEmbeddedStruct.Name
		*o = PipelineStepStateCompletedExpired(varPipelineStepStateCompletedExpired)
	} else {
		return err
	}

	varPipelineStepStateCompletedExpired := _PipelineStepStateCompletedExpired{}

	err = json.Unmarshal(bytes, &varPipelineStepStateCompletedExpired)
	if err == nil {
		o.PipelineStepStateCompletedResult = varPipelineStepStateCompletedExpired.PipelineStepStateCompletedResult
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")

		// remove fields from embedded structs
		reflectPipelineStepStateCompletedResult := reflect.ValueOf(o.PipelineStepStateCompletedResult)
		for i := 0; i < reflectPipelineStepStateCompletedResult.Type().NumField(); i++ {
			t := reflectPipelineStepStateCompletedResult.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineStepStateCompletedExpired struct {
	value *PipelineStepStateCompletedExpired
	isSet bool
}

func (v NullablePipelineStepStateCompletedExpired) Get() *PipelineStepStateCompletedExpired {
	return v.value
}

func (v *NullablePipelineStepStateCompletedExpired) Set(val *PipelineStepStateCompletedExpired) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStepStateCompletedExpired) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStepStateCompletedExpired) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStepStateCompletedExpired(val *PipelineStepStateCompletedExpired) *NullablePipelineStepStateCompletedExpired {
	return &NullablePipelineStepStateCompletedExpired{value: val, isSet: true}
}

func (v NullablePipelineStepStateCompletedExpired) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStepStateCompletedExpired) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


