/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
)

// PipelineCompletedError A Bitbucket Pipelines ERROR pipeline result.
type PipelineCompletedError struct {
	// The name of the result (ERROR)
	Name *string `json:"name,omitempty"`
	Error *PipelineError `json:"error,omitempty"`
}

// NewPipelineCompletedError instantiates a new PipelineCompletedError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineCompletedError() *PipelineCompletedError {
	this := PipelineCompletedError{}
	return &this
}

// NewPipelineCompletedErrorWithDefaults instantiates a new PipelineCompletedError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineCompletedErrorWithDefaults() *PipelineCompletedError {
	this := PipelineCompletedError{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PipelineCompletedError) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineCompletedError) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PipelineCompletedError) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PipelineCompletedError) SetName(v string) {
	o.Name = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PipelineCompletedError) GetError() PipelineError {
	if o == nil || o.Error == nil {
		var ret PipelineError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineCompletedError) GetErrorOk() (*PipelineError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PipelineCompletedError) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given PipelineError and assigns it to the Error field.
func (o *PipelineCompletedError) SetError(v PipelineError) {
	o.Error = &v
}

func (o PipelineCompletedError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullablePipelineCompletedError struct {
	value *PipelineCompletedError
	isSet bool
}

func (v NullablePipelineCompletedError) Get() *PipelineCompletedError {
	return v.value
}

func (v *NullablePipelineCompletedError) Set(val *PipelineCompletedError) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineCompletedError) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineCompletedError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineCompletedError(val *PipelineCompletedError) *NullablePipelineCompletedError {
	return &NullablePipelineCompletedError{value: val, isSet: true}
}

func (v NullablePipelineCompletedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineCompletedError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


