/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// PipelineScheduleExecutionErrored struct for PipelineScheduleExecutionErrored
type PipelineScheduleExecutionErrored struct {
	PipelineScheduleExecution
	Error *PipelineError `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PipelineScheduleExecutionErrored PipelineScheduleExecutionErrored

// NewPipelineScheduleExecutionErrored instantiates a new PipelineScheduleExecutionErrored object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineScheduleExecutionErrored() *PipelineScheduleExecutionErrored {
	this := PipelineScheduleExecutionErrored{}
	return &this
}

// NewPipelineScheduleExecutionErroredWithDefaults instantiates a new PipelineScheduleExecutionErrored object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineScheduleExecutionErroredWithDefaults() *PipelineScheduleExecutionErrored {
	this := PipelineScheduleExecutionErrored{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PipelineScheduleExecutionErrored) GetError() PipelineError {
	if o == nil || o.Error == nil {
		var ret PipelineError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineScheduleExecutionErrored) GetErrorOk() (*PipelineError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PipelineScheduleExecutionErrored) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given PipelineError and assigns it to the Error field.
func (o *PipelineScheduleExecutionErrored) SetError(v PipelineError) {
	o.Error = &v
}

func (o PipelineScheduleExecutionErrored) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedPipelineScheduleExecution, errPipelineScheduleExecution := json.Marshal(o.PipelineScheduleExecution)
	if errPipelineScheduleExecution != nil {
		return []byte{}, errPipelineScheduleExecution
	}
	errPipelineScheduleExecution = json.Unmarshal([]byte(serializedPipelineScheduleExecution), &toSerialize)
	if errPipelineScheduleExecution != nil {
		return []byte{}, errPipelineScheduleExecution
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *PipelineScheduleExecutionErrored) UnmarshalJSON(bytes []byte) (err error) {
	type PipelineScheduleExecutionErroredWithoutEmbeddedStruct struct {
		Error *PipelineError `json:"error,omitempty"`
	}

	varPipelineScheduleExecutionErroredWithoutEmbeddedStruct := PipelineScheduleExecutionErroredWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varPipelineScheduleExecutionErroredWithoutEmbeddedStruct)
	if err == nil {
		varPipelineScheduleExecutionErrored := _PipelineScheduleExecutionErrored{}
		varPipelineScheduleExecutionErrored.Error = varPipelineScheduleExecutionErroredWithoutEmbeddedStruct.Error
		*o = PipelineScheduleExecutionErrored(varPipelineScheduleExecutionErrored)
	} else {
		return err
	}

	varPipelineScheduleExecutionErrored := _PipelineScheduleExecutionErrored{}

	err = json.Unmarshal(bytes, &varPipelineScheduleExecutionErrored)
	if err == nil {
		o.PipelineScheduleExecution = varPipelineScheduleExecutionErrored.PipelineScheduleExecution
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "error")

		// remove fields from embedded structs
		reflectPipelineScheduleExecution := reflect.ValueOf(o.PipelineScheduleExecution)
		for i := 0; i < reflectPipelineScheduleExecution.Type().NumField(); i++ {
			t := reflectPipelineScheduleExecution.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePipelineScheduleExecutionErrored struct {
	value *PipelineScheduleExecutionErrored
	isSet bool
}

func (v NullablePipelineScheduleExecutionErrored) Get() *PipelineScheduleExecutionErrored {
	return v.value
}

func (v *NullablePipelineScheduleExecutionErrored) Set(val *PipelineScheduleExecutionErrored) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineScheduleExecutionErrored) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineScheduleExecutionErrored) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineScheduleExecutionErrored(val *PipelineScheduleExecutionErrored) *NullablePipelineScheduleExecutionErrored {
	return &NullablePipelineScheduleExecutionErrored{value: val, isSet: true}
}

func (v NullablePipelineScheduleExecutionErrored) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineScheduleExecutionErrored) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


