/*
Bitbucket API

Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.

API version: 2.0
Contact: support@bitbucket.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucket

import (
	"encoding/json"
	"reflect"
	"strings"
)

// JiraSite struct for JiraSite
type JiraSite struct {
	Object
	AdditionalProperties map[string]interface{}
}

type _JiraSite JiraSite

// NewJiraSite instantiates a new JiraSite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJiraSite() *JiraSite {
	this := JiraSite{}
	return &this
}

// NewJiraSiteWithDefaults instantiates a new JiraSite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJiraSiteWithDefaults() *JiraSite {
	this := JiraSite{}
	return &this
}

func (o JiraSite) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedObject, errObject := json.Marshal(o.Object)
	if errObject != nil {
		return []byte{}, errObject
	}
	errObject = json.Unmarshal([]byte(serializedObject), &toSerialize)
	if errObject != nil {
		return []byte{}, errObject
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *JiraSite) UnmarshalJSON(bytes []byte) (err error) {
	type JiraSiteWithoutEmbeddedStruct struct {
	}

	varJiraSiteWithoutEmbeddedStruct := JiraSiteWithoutEmbeddedStruct{}

	err = json.Unmarshal(bytes, &varJiraSiteWithoutEmbeddedStruct)
	if err == nil {
		varJiraSite := _JiraSite{}
		*o = JiraSite(varJiraSite)
	} else {
		return err
	}

	varJiraSite := _JiraSite{}

	err = json.Unmarshal(bytes, &varJiraSite)
	if err == nil {
		o.Object = varJiraSite.Object
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectObject := reflect.ValueOf(o.Object)
		for i := 0; i < reflectObject.Type().NumField(); i++ {
			t := reflectObject.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJiraSite struct {
	value *JiraSite
	isSet bool
}

func (v NullableJiraSite) Get() *JiraSite {
	return v.value
}

func (v *NullableJiraSite) Set(val *JiraSite) {
	v.value = val
	v.isSet = true
}

func (v NullableJiraSite) IsSet() bool {
	return v.isSet
}

func (v *NullableJiraSite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJiraSite(val *JiraSite) *NullableJiraSite {
	return &NullableJiraSite{value: val, isSet: true}
}

func (v NullableJiraSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJiraSite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


